#!/bin/sh

# get the num of columns from the first parameter
columns=$1
# if number of columns are less than 1, display error message and exit
if [ $columns -lt 1 ]
then
  >&2 echo "You have entered less than 1 columns to display, the number should be 1 or more."
  exit 1
fi
# shift so that all the other positional params are picture names
shift
# initialize count of invalid vars
invalidCount=0
# set total num of pictures to be the rest of the parameters
totalPictures=$#
# output the header that's the same for every input
echo "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">"
echo "<html>"
echo "  <head>"
echo "    <title>Pictures</title>"
echo "  </head>"
echo "<body>"
echo "  <h1>Pictures</h1>"
echo " <table>"
# put the unfinished column at the top
# set extra number of pics to be total mod num of columns
extraPics=`expr $totalPictures % $columns`
# if there are extra pics
if [ $extraPics -ne 0 ]
then
  # iterate through the extra set and display them on the first row
  # set the counter to be 0
  count=0
  echo "  <tr>"
  # while the curr pic number is less than # of extra pics
    while [ $count -lt $extraPics ]
    do
      # if the pics have a valid file format then display it
      extension=$(echo `file $1` | cut -d ' ' -f 2-4)
      if [ "$extension" = "JPEG image data," ]
      then
        echo "    <td><img src=\"$1\" height=100></td>"
      # otherwise increment invalid count
      else
        invalidCount=$((invalidCount+1))
      fi
      # increment count
      count=$((count+1))
      # shift the number of params down
      shift
    done
    echo "  </tr>"
  fi
# now outputting the normal complete rows
# while there are still more pictures in the parameters left
while [ $# -gt 0 ]
do
  echo "  <tr>"
  # set current column to be 0
  currCol=0
  # while current col number is less than the set number of columns
  while [ $currCol -lt $columns ]
  do
    # if the file is the correct format, output it in the table
    extension=$(echo `file -b $1` | cut -d ' ' -f 1-3)
    if [ "$extension" = "JPEG image data," ]
    then
      echo "    <td><img src=\"$1\" height=100></td>"
    # otherwise increment invalid count
    else
      invalidCount=$((invalidCount+1))
    fi
    # go to the next column
    currCol=$((currCol+1))
    # shift the parameters down
    shift
  done
  echo "  </tr>"
done
# add the bottom of the page that is the same for every input
echo " </table>"
echo "</body> </html>"
# if there are invalid file extensions, output error message
if [ $invalidCount -ne 0 ]
then
  >&2 echo "You have inserted $invalidCount file(s) with invalid file extensions."
fi
